version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app/
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: